name: Build and Push to Cachix

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Cachix
        uses: cachix/cachix-action@v17
        with:
          name: aic8800-nix
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

      - name: Build latest kernel package
        run: nix build .#latest --accept-flake-config -L
